# == Schema Information
#
# Table name: customer_services
#
#  id             :integer          not null, primary key
#  name           :string
#  phone          :string
#  subdistrict_id :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#
# Indexes
#
#  index_customer_services_on_subdistrict_id  (subdistrict_id)
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CustomerServicesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CustomerService. As you add validations to CustomerService, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomerServicesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all customer_services as @customer_services" do
      customer_service = CustomerService.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:customer_services)).to eq([customer_service])
    end
  end

  describe "GET #show" do
    it "assigns the requested customer_service as @customer_service" do
      customer_service = CustomerService.create! valid_attributes
      get :show, {:id => customer_service.to_param}, valid_session
      expect(assigns(:customer_service)).to eq(customer_service)
    end
  end

  describe "GET #new" do
    it "assigns a new customer_service as @customer_service" do
      get :new, {}, valid_session
      expect(assigns(:customer_service)).to be_a_new(CustomerService)
    end
  end

  describe "GET #edit" do
    it "assigns the requested customer_service as @customer_service" do
      customer_service = CustomerService.create! valid_attributes
      get :edit, {:id => customer_service.to_param}, valid_session
      expect(assigns(:customer_service)).to eq(customer_service)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CustomerService" do
        expect {
          post :create, {:customer_service => valid_attributes}, valid_session
        }.to change(CustomerService, :count).by(1)
      end

      it "assigns a newly created customer_service as @customer_service" do
        post :create, {:customer_service => valid_attributes}, valid_session
        expect(assigns(:customer_service)).to be_a(CustomerService)
        expect(assigns(:customer_service)).to be_persisted
      end

      it "redirects to the created customer_service" do
        post :create, {:customer_service => valid_attributes}, valid_session
        expect(response).to redirect_to(CustomerService.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved customer_service as @customer_service" do
        post :create, {:customer_service => invalid_attributes}, valid_session
        expect(assigns(:customer_service)).to be_a_new(CustomerService)
      end

      it "re-renders the 'new' template" do
        post :create, {:customer_service => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested customer_service" do
        customer_service = CustomerService.create! valid_attributes
        put :update, {:id => customer_service.to_param, :customer_service => new_attributes}, valid_session
        customer_service.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested customer_service as @customer_service" do
        customer_service = CustomerService.create! valid_attributes
        put :update, {:id => customer_service.to_param, :customer_service => valid_attributes}, valid_session
        expect(assigns(:customer_service)).to eq(customer_service)
      end

      it "redirects to the customer_service" do
        customer_service = CustomerService.create! valid_attributes
        put :update, {:id => customer_service.to_param, :customer_service => valid_attributes}, valid_session
        expect(response).to redirect_to(customer_service)
      end
    end

    context "with invalid params" do
      it "assigns the customer_service as @customer_service" do
        customer_service = CustomerService.create! valid_attributes
        put :update, {:id => customer_service.to_param, :customer_service => invalid_attributes}, valid_session
        expect(assigns(:customer_service)).to eq(customer_service)
      end

      it "re-renders the 'edit' template" do
        customer_service = CustomerService.create! valid_attributes
        put :update, {:id => customer_service.to_param, :customer_service => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested customer_service" do
      customer_service = CustomerService.create! valid_attributes
      expect {
        delete :destroy, {:id => customer_service.to_param}, valid_session
      }.to change(CustomerService, :count).by(-1)
    end

    it "redirects to the customer_services list" do
      customer_service = CustomerService.create! valid_attributes
      delete :destroy, {:id => customer_service.to_param}, valid_session
      expect(response).to redirect_to(customer_services_url)
    end
  end

end
