# == Schema Information
#
# Table name: news_sorts
#
#  id             :integer          not null, primary key
#  rank           :integer
#  title          :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  subdistrict_id :integer
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe NewsSortsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # NewsSort. As you add validations to NewsSort, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewsSortsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all news_sorts as @news_sorts" do
      news_sort = NewsSort.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:news_sorts)).to eq([news_sort])
    end
  end

  describe "GET #show" do
    it "assigns the requested news_sort as @news_sort" do
      news_sort = NewsSort.create! valid_attributes
      get :show, {:id => news_sort.to_param}, valid_session
      expect(assigns(:news_sort)).to eq(news_sort)
    end
  end

  describe "GET #new" do
    it "assigns a new news_sort as @news_sort" do
      get :new, {}, valid_session
      expect(assigns(:news_sort)).to be_a_new(NewsSort)
    end
  end

  describe "GET #edit" do
    it "assigns the requested news_sort as @news_sort" do
      news_sort = NewsSort.create! valid_attributes
      get :edit, {:id => news_sort.to_param}, valid_session
      expect(assigns(:news_sort)).to eq(news_sort)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new NewsSort" do
        expect {
          post :create, {:news_sort => valid_attributes}, valid_session
        }.to change(NewsSort, :count).by(1)
      end

      it "assigns a newly created news_sort as @news_sort" do
        post :create, {:news_sort => valid_attributes}, valid_session
        expect(assigns(:news_sort)).to be_a(NewsSort)
        expect(assigns(:news_sort)).to be_persisted
      end

      it "redirects to the created news_sort" do
        post :create, {:news_sort => valid_attributes}, valid_session
        expect(response).to redirect_to(NewsSort.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved news_sort as @news_sort" do
        post :create, {:news_sort => invalid_attributes}, valid_session
        expect(assigns(:news_sort)).to be_a_new(NewsSort)
      end

      it "re-renders the 'new' template" do
        post :create, {:news_sort => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested news_sort" do
        news_sort = NewsSort.create! valid_attributes
        put :update, {:id => news_sort.to_param, :news_sort => new_attributes}, valid_session
        news_sort.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested news_sort as @news_sort" do
        news_sort = NewsSort.create! valid_attributes
        put :update, {:id => news_sort.to_param, :news_sort => valid_attributes}, valid_session
        expect(assigns(:news_sort)).to eq(news_sort)
      end

      it "redirects to the news_sort" do
        news_sort = NewsSort.create! valid_attributes
        put :update, {:id => news_sort.to_param, :news_sort => valid_attributes}, valid_session
        expect(response).to redirect_to(news_sort)
      end
    end

    context "with invalid params" do
      it "assigns the news_sort as @news_sort" do
        news_sort = NewsSort.create! valid_attributes
        put :update, {:id => news_sort.to_param, :news_sort => invalid_attributes}, valid_session
        expect(assigns(:news_sort)).to eq(news_sort)
      end

      it "re-renders the 'edit' template" do
        news_sort = NewsSort.create! valid_attributes
        put :update, {:id => news_sort.to_param, :news_sort => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested news_sort" do
      news_sort = NewsSort.create! valid_attributes
      expect {
        delete :destroy, {:id => news_sort.to_param}, valid_session
      }.to change(NewsSort, :count).by(-1)
    end

    it "redirects to the news_sorts list" do
      news_sort = NewsSort.create! valid_attributes
      delete :destroy, {:id => news_sort.to_param}, valid_session
      expect(response).to redirect_to(news_sorts_url)
    end
  end

end
